package org.scottishtecharmy.soundscape.services.mediacontrol

import android.content.Intent
import android.util.Log
import android.view.KeyEvent
import androidx.annotation.OptIn
import androidx.core.content.IntentCompat
import androidx.media3.common.util.UnstableApi
import androidx.media3.session.MediaSession

@UnstableApi
/** This callback class handles media button events generated by bluetooth headphones etc.
 * These are then mapped to specific Soundscape features.
 */
class SoundscapeMediaSessionCallback(
    private val getTarget: () -> MediaControlTarget
):
    MediaSession.Callback {
    // Configure commands available to the controller in onConnect()
    @OptIn(UnstableApi::class)
    override fun onConnect(
        session: MediaSession,
        controller: MediaSession.ControllerInfo
    ): MediaSession.ConnectionResult {

        Log.e("SoundscapeMediaSession", "onConnect")
        val sessionCommands = MediaSession.ConnectionResult.DEFAULT_SESSION_COMMANDS
        return MediaSession.ConnectionResult.AcceptedResultBuilder(session)
            .setAvailableSessionCommands(sessionCommands)
            .build()
    }

    override fun onMediaButtonEvent(
        session: MediaSession,
        controllerInfo: MediaSession.ControllerInfo,
        intent: Intent
    ): Boolean {

        val keyEvent : KeyEvent? = IntentCompat.getParcelableExtra(
            intent,
            Intent.EXTRA_KEY_EVENT,
            KeyEvent::class.java
        )

        // Ignore key-up events to prevent double-firing
        if (keyEvent?.action != KeyEvent.ACTION_DOWN) return false

        // So far I've only seen KEYCODE_MEDIA_PLAY_PAUSE, KEYCODE_MEDIA_PREVIOUS and
        // KEYCODE_MEDIA_NEXT, though that may be specific to my phone. The only event actually
        // handled for now is KEYCODE_MEDIA_NEXT.

        // TODO:
        //  The behaviour of the media buttons changes when a route is being played back. In that
        //  case the buttons map to next/previous waypoint and muting audio. This currently doesn't
        //  play nicely with the audioMenu, more work is required.

        keyEvent?.let { event ->
            val decodedKey = when(event.keyCode) {
                KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE -> {
                    // ⏯ Play/Pause: Mute any current callouts and if the audio beacon is set, toggle the beacon audio.
                    getTarget().onPlayPause()
                    "Play/Pause"
                }
                KeyEvent.KEYCODE_MEDIA_SKIP_FORWARD -> {
                    // ⏩ Skip Forward
                    getTarget().onNext()
                    "Skip forward"
                }
                KeyEvent.KEYCODE_MEDIA_NEXT -> {
                    // ⏭ Next
                    getTarget().onNext()
                    "Next"
                }

                KeyEvent.KEYCODE_MEDIA_PREVIOUS -> {
                    // ⏮ Previous
                    getTarget().onPrevious()
                }
                KeyEvent.KEYCODE_MEDIA_SKIP_BACKWARD -> {
                    // ⏪ Skip Backward
                    getTarget().onPrevious()
                    "Skip backward"
                }

                KeyEvent.KEYCODE_MEDIA_FAST_FORWARD -> "Fast forward"
                KeyEvent.KEYCODE_MEDIA_REWIND -> "Rewind"
                else -> return false
            }
            Log.e("SoundscapeMediaSession", "onMediaButtonEvent ${event.keyCode} $decodedKey")
            return true
        }
        return false
    }
}